package com.point72.alarm.center.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.point72.alarm.center.model.Department;

@Mapper
public interface DepartmentMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pmp_department
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pmp_department
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	int insert(Department record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pmp_department
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	int insertSelective(Department record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pmp_department
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	Department selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pmp_department
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	int updateByPrimaryKeySelective(Department record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pmp_department
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	int updateByPrimaryKey(Department record);

	List<Department> findTree();

	List<Department> selectParentById(String id);
}