package com.point72.alarm.center.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.point72.alarm.center.model.User;

@Mapper
public interface UserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pmp_user
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pmp_user
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pmp_user
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pmp_user
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	User selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pmp_user
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pmp_user
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	int updateByPrimaryKey(User record);
}