package com.inno72.alarm.center.model;

import java.io.Serializable;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.id
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.userid
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.name
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.tel
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.work_place
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private String workPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.remark
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.mobile
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.email
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.org_email
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private String orgEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.order_in_depts
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private String orderInDepts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.active
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private Boolean active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.is_admin
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private Boolean isAdmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.is_boss
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private Boolean isBoss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.ding_id
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private String dingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.unionid
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private String unionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.is_leader_in_depts
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private Boolean isLeaderInDepts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.is_hide
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private Boolean isHide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.position
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.avatar
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.jobnumber
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private String jobnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.user_name
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.persistent_code
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private String persistentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pmp_user
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.id
     *
     * @return the value of pmp_user.id
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.id
     *
     * @param id the value for pmp_user.id
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.userid
     *
     * @return the value of pmp_user.userid
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.userid
     *
     * @param userid the value for pmp_user.userid
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.name
     *
     * @return the value of pmp_user.name
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.name
     *
     * @param name the value for pmp_user.name
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.tel
     *
     * @return the value of pmp_user.tel
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.tel
     *
     * @param tel the value for pmp_user.tel
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.work_place
     *
     * @return the value of pmp_user.work_place
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public String getWorkPlace() {
        return workPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.work_place
     *
     * @param workPlace the value for pmp_user.work_place
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setWorkPlace(String workPlace) {
        this.workPlace = workPlace == null ? null : workPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.remark
     *
     * @return the value of pmp_user.remark
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.remark
     *
     * @param remark the value for pmp_user.remark
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.mobile
     *
     * @return the value of pmp_user.mobile
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.mobile
     *
     * @param mobile the value for pmp_user.mobile
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.email
     *
     * @return the value of pmp_user.email
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.email
     *
     * @param email the value for pmp_user.email
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.org_email
     *
     * @return the value of pmp_user.org_email
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public String getOrgEmail() {
        return orgEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.org_email
     *
     * @param orgEmail the value for pmp_user.org_email
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setOrgEmail(String orgEmail) {
        this.orgEmail = orgEmail == null ? null : orgEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.order_in_depts
     *
     * @return the value of pmp_user.order_in_depts
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public String getOrderInDepts() {
        return orderInDepts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.order_in_depts
     *
     * @param orderInDepts the value for pmp_user.order_in_depts
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setOrderInDepts(String orderInDepts) {
        this.orderInDepts = orderInDepts == null ? null : orderInDepts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.active
     *
     * @return the value of pmp_user.active
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.active
     *
     * @param active the value for pmp_user.active
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.is_admin
     *
     * @return the value of pmp_user.is_admin
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public Boolean getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.is_admin
     *
     * @param isAdmin the value for pmp_user.is_admin
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.is_boss
     *
     * @return the value of pmp_user.is_boss
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public Boolean getIsBoss() {
        return isBoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.is_boss
     *
     * @param isBoss the value for pmp_user.is_boss
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setIsBoss(Boolean isBoss) {
        this.isBoss = isBoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.ding_id
     *
     * @return the value of pmp_user.ding_id
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public String getDingId() {
        return dingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.ding_id
     *
     * @param dingId the value for pmp_user.ding_id
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setDingId(String dingId) {
        this.dingId = dingId == null ? null : dingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.unionid
     *
     * @return the value of pmp_user.unionid
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.unionid
     *
     * @param unionid the value for pmp_user.unionid
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.is_leader_in_depts
     *
     * @return the value of pmp_user.is_leader_in_depts
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public Boolean getIsLeaderInDepts() {
        return isLeaderInDepts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.is_leader_in_depts
     *
     * @param isLeaderInDepts the value for pmp_user.is_leader_in_depts
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setIsLeaderInDepts(Boolean isLeaderInDepts) {
        this.isLeaderInDepts = isLeaderInDepts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.is_hide
     *
     * @return the value of pmp_user.is_hide
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public Boolean getIsHide() {
        return isHide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.is_hide
     *
     * @param isHide the value for pmp_user.is_hide
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setIsHide(Boolean isHide) {
        this.isHide = isHide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.position
     *
     * @return the value of pmp_user.position
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.position
     *
     * @param position the value for pmp_user.position
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.avatar
     *
     * @return the value of pmp_user.avatar
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.avatar
     *
     * @param avatar the value for pmp_user.avatar
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.jobnumber
     *
     * @return the value of pmp_user.jobnumber
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public String getJobnumber() {
        return jobnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.jobnumber
     *
     * @param jobnumber the value for pmp_user.jobnumber
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setJobnumber(String jobnumber) {
        this.jobnumber = jobnumber == null ? null : jobnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.user_name
     *
     * @return the value of pmp_user.user_name
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.user_name
     *
     * @param userName the value for pmp_user.user_name
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.persistent_code
     *
     * @return the value of pmp_user.persistent_code
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public String getPersistentCode() {
        return persistentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.persistent_code
     *
     * @param persistentCode the value for pmp_user.persistent_code
     *
     * @mbggenerated Wed Jun 28 12:58:41 CST 2017
     */
    public void setPersistentCode(String persistentCode) {
        this.persistentCode = persistentCode == null ? null : persistentCode.trim();
    }
}