package com.point72.alarm.center.model;

import java.io.Serializable;
import java.util.List;

public class Department implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pmp_department.id
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pmp_department.name
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pmp_department.order_num
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	private Integer orderNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pmp_department.parent_id
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	private String parentId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pmp_department.create_dept_group
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	private Boolean createDeptGroup;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pmp_department.auto_add_user
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	private Boolean autoAddUser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pmp_department.dept_hiding
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	private Boolean deptHiding;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pmp_department.dept_perimits
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	private String deptPerimits;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pmp_department.user_perimits
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	private String userPerimits;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pmp_department.outer_dept
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	private Boolean outerDept;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pmp_department.outer_permit_depts
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	private String outerPermitDepts;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pmp_department.outer_permit_users
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	private String outerPermitUsers;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pmp_department.org_dept_owner
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	private String orgDeptOwner;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pmp_department.dept_manager_userid_list
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	private String deptManagerUseridList;

	private List<Department> children;

	private List<User> user;

	public List<Department> getChildren() {
		return children;
	}

	public void setChildren(List<Department> children) {
		this.children = children;
	}

	public List<User> getUser() {
		return user;
	}

	public void setUser(List<User> user) {
		this.user = user;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table pmp_department
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pmp_department.id
	 *
	 * @return the value of pmp_department.id
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pmp_department.id
	 *
	 * @param id
	 *            the value for pmp_department.id
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pmp_department.name
	 *
	 * @return the value of pmp_department.name
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pmp_department.name
	 *
	 * @param name
	 *            the value for pmp_department.name
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pmp_department.order_num
	 *
	 * @return the value of pmp_department.order_num
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public Integer getOrderNum() {
		return orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pmp_department.order_num
	 *
	 * @param orderNum
	 *            the value for pmp_department.order_num
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pmp_department.parent_id
	 *
	 * @return the value of pmp_department.parent_id
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pmp_department.parent_id
	 *
	 * @param parentId
	 *            the value for pmp_department.parent_id
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId == null ? null : parentId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pmp_department.create_dept_group
	 *
	 * @return the value of pmp_department.create_dept_group
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public Boolean getCreateDeptGroup() {
		return createDeptGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pmp_department.create_dept_group
	 *
	 * @param createDeptGroup
	 *            the value for pmp_department.create_dept_group
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public void setCreateDeptGroup(Boolean createDeptGroup) {
		this.createDeptGroup = createDeptGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pmp_department.auto_add_user
	 *
	 * @return the value of pmp_department.auto_add_user
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public Boolean getAutoAddUser() {
		return autoAddUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pmp_department.auto_add_user
	 *
	 * @param autoAddUser
	 *            the value for pmp_department.auto_add_user
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public void setAutoAddUser(Boolean autoAddUser) {
		this.autoAddUser = autoAddUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pmp_department.dept_hiding
	 *
	 * @return the value of pmp_department.dept_hiding
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public Boolean getDeptHiding() {
		return deptHiding;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pmp_department.dept_hiding
	 *
	 * @param deptHiding
	 *            the value for pmp_department.dept_hiding
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public void setDeptHiding(Boolean deptHiding) {
		this.deptHiding = deptHiding;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pmp_department.dept_perimits
	 *
	 * @return the value of pmp_department.dept_perimits
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public String getDeptPerimits() {
		return deptPerimits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pmp_department.dept_perimits
	 *
	 * @param deptPerimits
	 *            the value for pmp_department.dept_perimits
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public void setDeptPerimits(String deptPerimits) {
		this.deptPerimits = deptPerimits == null ? null : deptPerimits.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pmp_department.user_perimits
	 *
	 * @return the value of pmp_department.user_perimits
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public String getUserPerimits() {
		return userPerimits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pmp_department.user_perimits
	 *
	 * @param userPerimits
	 *            the value for pmp_department.user_perimits
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public void setUserPerimits(String userPerimits) {
		this.userPerimits = userPerimits == null ? null : userPerimits.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pmp_department.outer_dept
	 *
	 * @return the value of pmp_department.outer_dept
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public Boolean getOuterDept() {
		return outerDept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pmp_department.outer_dept
	 *
	 * @param outerDept
	 *            the value for pmp_department.outer_dept
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public void setOuterDept(Boolean outerDept) {
		this.outerDept = outerDept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pmp_department.outer_permit_depts
	 *
	 * @return the value of pmp_department.outer_permit_depts
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public String getOuterPermitDepts() {
		return outerPermitDepts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pmp_department.outer_permit_depts
	 *
	 * @param outerPermitDepts
	 *            the value for pmp_department.outer_permit_depts
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public void setOuterPermitDepts(String outerPermitDepts) {
		this.outerPermitDepts = outerPermitDepts == null ? null : outerPermitDepts.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pmp_department.outer_permit_users
	 *
	 * @return the value of pmp_department.outer_permit_users
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public String getOuterPermitUsers() {
		return outerPermitUsers;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pmp_department.outer_permit_users
	 *
	 * @param outerPermitUsers
	 *            the value for pmp_department.outer_permit_users
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public void setOuterPermitUsers(String outerPermitUsers) {
		this.outerPermitUsers = outerPermitUsers == null ? null : outerPermitUsers.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pmp_department.org_dept_owner
	 *
	 * @return the value of pmp_department.org_dept_owner
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public String getOrgDeptOwner() {
		return orgDeptOwner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pmp_department.org_dept_owner
	 *
	 * @param orgDeptOwner
	 *            the value for pmp_department.org_dept_owner
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public void setOrgDeptOwner(String orgDeptOwner) {
		this.orgDeptOwner = orgDeptOwner == null ? null : orgDeptOwner.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pmp_department.dept_manager_userid_list
	 *
	 * @return the value of pmp_department.dept_manager_userid_list
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public String getDeptManagerUseridList() {
		return deptManagerUseridList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pmp_department.dept_manager_userid_list
	 *
	 * @param deptManagerUseridList
	 *            the value for pmp_department.dept_manager_userid_list
	 *
	 * @mbggenerated Wed Jun 28 12:58:41 CST 2017
	 */
	public void setDeptManagerUseridList(String deptManagerUseridList) {
		this.deptManagerUseridList = deptManagerUseridList == null ? null : deptManagerUseridList.trim();
	}
}